language: go

sudo: false

go:
  - master
  - 1.9.x
  - 1.10.x
  
env:
  - TEST_EXTERNAL=1

matrix:
  allow_failures:
    - go: 1.9.x
    - go: master
  fast_finish: true

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
 - go get -v -t .

script:
 - go test -tags gofuzz -run TestFuzz -v .
 - $HOME/gopath/bin/goveralls -service=travis-ci -v -package .
